#!/bin/bash
while [ "$1" != "" ]
do
    case "$1" in
            frontend)
                docker-compose -f docker-compose.build.frontend.yml build
                ;;

            backend)
                docker-compose -f docker-compose.build.backend.yml build
                ;;
            
            -h | --help)
                echo $"Usage: $0 {frontend|backend}"
                exit 1
    
    esac
    shift
done
