FROM ubuntu:18.04

RUN mkdir /backup

# Set timezone
ENV TZ Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set LANG
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

RUN apt-get update -y && apt-get install -y curl gnupg2 \
    && echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list \
    && curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && apt-get update -y \
    && apt-get install -y postgresql-12-postgis-3 \
    && rm -rf /var/lib/apt/lists/*

# Postgresql disallow root user to start
USER postgres
RUN /etc/init.d/postgresql start \
    && psql --command "CREATE USER antarctic WITH SUPERUSER PASSWORD 'antarctic';" \
    && createdb -O antarctic antarctic \
    && psql -d antarctic --command "CREATE EXTENSION postgis;"

# Allow any connection in development mode
RUN echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/12/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/12/main/postgresql.conf

# Expose the PostgreSQL port
EXPOSE 5432

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# Start postgresql and allow attach
CMD ["/usr/lib/postgresql/12/bin/postgres", "-D", "/var/lib/postgresql/12/main", "-c", "config_file=/etc/postgresql/12/main/postgresql.conf"]