FROM ubuntu:18.04

ARG NODE_VERSION=v12.18.2

# Set timezone
ENV TZ Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set LANG
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

ENV PATH /yarnpkg/yarn-v1.22.4/bin:/nodejs/node-${NODE_VERSION}-linux-x64/bin:$PATH

RUN apt-get update -y \
    && apt-get install -y \
        gnupg2 build-essential \
        wget \
    && wget -q -O node.tar.xz https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz \
    && wget -q -O yarn.tar.gz https://github.com/yarnpkg/yarn/releases/download/v1.22.4/yarn-v1.22.4.tar.gz \
    && mkdir -p /nodejs && mkdir -p /yarnpkg \
    && tar -xJf node.tar.xz -C /nodejs \
    && rm node.tar.xz \
    && tar -xzf yarn.tar.gz -C /yarnpkg \
    && rm yarn.tar.gz \
    && apt-get clean && rm -rf /var/lib/apt/lists/* 

RUN echo "nameserver 1.1.1.1" >> /etc/resolv.conf

VOLUME  ["/code"]
WORKDIR /code
EXPOSE 9000
