# Generated by Django 3.0.8 on 2020-08-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaice',
            name='png_name',
            field=models.CharField(default='aaa', max_length=20),
            preserve_default=False,
        ),
    ]
